# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Glad_config = debug
  ImGui_config = debug
  Psyche_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  Glad_config = release
  ImGui_config = release
  Psyche_config = release
  Sandbox_config = release

else ifeq ($(config),dist)
  Glad_config = dist
  ImGui_config = dist
  Psyche_config = dist
  Sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Glad ImGui Psyche Sandbox

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: Glad ImGui

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Psyche/vendor/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Psyche/vendor/imgui -f Makefile config=$(ImGui_config)
endif

Psyche: Glad ImGui
ifneq (,$(Psyche_config))
	@echo "==== Building Psyche ($(Psyche_config)) ===="
	@${MAKE} --no-print-directory -C Psyche -f Makefile config=$(Psyche_config)
endif

Sandbox: Psyche Glad ImGui
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Psyche/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Psyche/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Psyche -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   Psyche"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"