#pragma once

// From glfw3.h
#define PSC_MOUSE_BUTTON_1      0
#define PSC_MOUSE_BUTTON_2      1
#define PSC_MOUSE_BUTTON_3      2
#define PSC_MOUSE_BUTTON_4      3
#define PSC_MOUSE_BUTTON_5      4
#define PSC_MOUSE_BUTTON_6      5
#define PSC_MOUSE_BUTTON_7      6
#define PSC_MOUSE_BUTTON_8      7
#define PSC_MOUSE_BUTTON_LAST   PSC_MOUSE_BUTTON_8
#define PSC_MOUSE_BUTTON_LEFT   PSC_MOUSE_BUTTON_1
#define PSC_MOUSE_BUTTON_RIGHT  PSC_MOUSE_BUTTON_2
#define PSC_MOUSE_BUTTON_MIDDLE PSC_MOUSE_BUTTON_3
